export const INPUT_HANDLER = "INPUT_HANDLER";

export const AUTH_START = "AUTH_START";

export const SIGN_UP_SUCCESS = "SIGN_UP_SUCCESS";
export const SIGN_UP_FAIL = "SIGN_UP_FAIL";

export const SIGN_IN_START = "SIGN_IN_START";
export const SIGN_IN_SUCCESS = "SIGN_IN_SUCCESS";
export const SIGN_IN_FAIL = "SIGN_IN_FAIL";
export const SET_LOCALID = "SET_LOCALID";

export const LOGOUT = "LOGOUT";

export const GET_HOT_STOCKS = "GET_HOT_STOCKS";

export const LOAD_NEWS_START = "LOAD_NEWS_START";
export const LOAD_NEWS_SUCCESS = "LOAD_NEWS_SUCCESS";
export const LOAD_NEWS_FAIL = "LOAD_NEWS_FAIL";
export const SET_CURRENT_PAGE = "SET_CURRENT_PAGE";
export const SET_NEXT_PAGE = "SET_NEXT_PAGE";
export const SET_PREVIOUS_PAGE = "SET_PREVIOUS_PAGE";

export const CHANGE_MODE = "CHANGE_MODE";

export const LOAD_BESTMATCHES_SUCCESS = "LOAD_BESTMATCHES_SUCCESS";
export const LOAD_BESTMATCHES_FAIL = "LOAD_BESTMATCHES_FAIL";
export const SAVE_SEARCH_INPUT_VALUE = "SAVE_SEARCH_INPUT_VALUE";
export const CLEAR_SEARCH_INPUT_VALUE = "CLEAR_SEARCH_INPUT_VALUE";
export const SAVE_AMOUNT_INPUT_VALUE = "SAVE_AMOUNT_INPUT_VALUE";
export const CLEAR_AMOUNT_INPUT_VALUE = "CLEAR_AMOUNT_INPUT_VALUE";
export const TOGGLE_AMOUNT_INPUT_MODE = "TOGGLE_AMOUNT_INPUT_MODE";
export const HANDLE_RESPONSES = "HANDLE_RESPONSES";
export const HANDLE_UPDATE = "HANDLE_UPDATE";
export const CLOSE_MESSAGE = "CLOSE_MESSAGE";
export const UPDATE_PORTFOLIO_STATS = "UPDATE_PORTFOLIO_STATS";
export const FINDATA_LOADING_TRUE = "FINDATA_LOADING_TRUE";
export const FINDATA_LOADING_FALSE = "FINDATA_LOADING_FALSE";

export const SET_LANGUAGE = "SET_LANGUAGE";
